### ISSUE TITLE
utilize a broadcast stream controler

### ISSUE THREAD

**Issue by pkubat** [jeffmikels/tcp_client_dart#2]
The stream controller should be a .brocast() as this will allow multiple listeners if needed,

I believe its line 73 that needs changed to broadcast()
```
final StreamController<Uint8List> _dataController = StreamController<Uint8List>.broadcast();
```

**Comment by jeffmikels** [comment]
I'm not sure I want to make this change. The main difference between broadcast streams and regular streams is that a broadcast stream will discard all data if there is no listener, but a normal stream will cache the data until there is a listener.

If you want to listen to the same stream multiple times, use the built-in Stream method `asBroadcastStream` to get a broadcast stream you can listen to multiple times.

Do you have another reason why we should prefer broadcast streams by default?
